# Start with CUDA Theano base image
FROM matthewelse/cuda-theano:8.0
MAINTAINER Kai Arulkumaran <design@kaixhin.com>

# Install bleeding-edge Lasagne
RUN pip install --upgrade https://github.com/Lasagne/Lasagne/archive/master.zip
